version: '3'

services:

  subquery-node:
    image: onfinality/subql-node:v1.10.2
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS:  
      DB_DATABASE: prod-polkadot-balance
      DB_HOST: 
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --log-level debug
      - --batch-size=10

